# main.py
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from .webpages import router as webpages_router
from .scrapes import router as scrapes_router

app = FastAPI(root_path="")
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# Used to manage webpages
app.include_router(webpages_router, prefix="/webpages", tags=["webpages"])

# Used to run scrapes and manage the data generated by them
app.include_router(scrapes_router, prefix="/scrapes", tags=["scrapes"])


@app.get("/")
def root():
    return {
        'msg': 'Hello world!'
    }
