<template>
    <div class="element-details-view">
        <h1>Element details</h1>
        <div class="element-details-grid">
            <CardBasic
                class="g-a"
                icon="bxs-info-circle"
                title="Element info"
                description="Inspect the details of the element"
            >
                <div class="flex-col gap-16">
                    <table>
                        <tbody>
                            <tr>
                                <th>Metric name</th>
                                <td>{{ element.metric_name }}</td>
                            </tr>
                            <tr>
                                <th>Locator string</th>
                                <td>{{ element.locator }}</td>
                            </tr>
                            <tr>
                                <th>Element ID</th>
                                <td>{{ element.element_id }}</td>
                            </tr>
                            <tr>
                                <th>Parent webpage</th>
                                <td>{{ parentWebpage.page_name }} #{{ parentWebpage.webpage_id }}</td>
                            </tr>
                            <tr>
                                <th>Data count</th>
                                <td>{{ dataCount }} datapoint{{ dataCount == 1 ? '' : 's' }}</td>
                            </tr>
                        </tbody>
                    </table>
                    <div class="flex-row gap-8">
                        <button @click="editElement" class="btn-with-icon">
                            <i class="bx bxs-edit"></i>
                            <span>Edit</span>
                        </button>
                        <button @click="deleteElement" class="btn-with-icon btn-danger">
                            <i class="bx bxs-trash"></i>
                            <span>Delete</span>
                        </button>
                    </div>
                </div>
            </CardBasic>

            <CardBasic
                class="g-b"
                icon="bxs-bar-chart-alt-2"
                title="Scraped data visualized" 
                description="View the scraped data in a graph"
            >
                <ChartLine
                    v-if="data.length > 0"
                    :chartData="data"
                />
                <ListingPlaceholder 
                    v-else
                    icon="bxs-bar-chart-alt-2"
                    text="No data found"
                    desc="The data scraped from the current element will be used to create a chart here."
                />
            </CardBasic>

            <CardBasic
                class="g-c"
                icon="bx bxs-file"
                title="Element logs"
                description="The logs from this elements scrapes."
            >
                <div class="vertical-scroll-list">
                    <LogEntry 
                        v-for="(log, index) in logs"
                        :key="index"
                        :log="log"
                        :enableTopLevelLinks="false"
                    />
                </div>
                <ListingPlaceholder
                    v-if="logs.length === 0"
                    icon="bx bxs-file"
                    text="No logs found"
                    desc="Logs generated by scraping will appear here."
                />
            </CardBasic>

            <CardBasic
                class="g-d"
                icon="bxs-data"
                title="Scraped element data"
                description="Inspect the data that has been scraped from the element"
            >
                <table v-if="data?.length > 0">
                    <tbody>
                        <tr>
                            <th>Data ID</th>
                            <th>Element ID</th>
                            <th>Value</th>
                            <th>Timestamp</th>
                        </tr>
                        <tr v-for="entry in data">
                            <td>{{ entry.data_id }}</td>
                            <td>{{ entry.element_id }}</td>
                            <td>{{ entry.value }}</td>
                            <td>{{ formatTimestamp(entry.created_at) }}</td>
                        </tr>
                    </tbody>
                </table>
                <ListingPlaceholder 
                    v-else
                    icon="bxs-data"
                    text="No data found"
                    desc="The data scraped from the current element will appear here."
                />
            </CardBasic>
        </div>

        <ModalElement ref="modalElementRef"/>
        <ModalConfirmation 
            ref="modalDeleteElementConfirmationRef"
            title="Delete Element"
            description="Are you sure you want to delete the element? All of the gathered data will be removed permanently. This action is irreversible!"
            optionNegative="Back to safety"
            optionPositive="Delete permanently"
            :redHover="true"
        />
    </div>
</template>

<script>
import CardBasic from '@/components/CardBasic.vue';
import FormElement from '@/components/FormElement.vue';
import ModalElement from '@/components/ModalElement.vue'
import ModalConfirmation from '@/components/ModalConfirmation.vue'
import { fastApi } from '@/utils/fastApi';
import { formatTimestamp } from '@/utils/utils';
import ChartLine from '@/components/ChartLine.vue';
import ListingPlaceholder from '@/components/ListingPlaceholder.vue';
import LogEntry from '@/components/LogEntry.vue';
import { useConfigStore } from '@/stores/config';

export default {
    name: 'ElementDetails',
    components: {
        CardBasic,
        FormElement,
        ModalElement,
        ModalConfirmation,
        ChartLine,
        ListingPlaceholder,
        LogEntry,
    },
    data() {
        return {
            element: {},
            parentWebpage: {},
            data: [],
            logs: [],
        }
    },
    methods: {
        async getElementInfo() {
            const response = await fastApi.elements.getById(this.$route.params.element_id);
            if (response) {
                this.element = response;
            }
        },
        async getElementData() {
            const response = await fastApi.elements.data(this.$route.params.element_id);
            if (response) {
                this.data = response
                    .map(entry => ({
                        ...entry,
                        metric_name: this.element.metric_name || '',
                    }))
            }
        },
        async getParentWebpageInfo() {
            const response = await fastApi.webpages.getById(this.$route.params.webpage_id);
            if (response) {
                this.parentWebpage = response;
            }
        },
        async getElementLogs() {
            const resp = await fastApi.elements.logs.get(this.$route.params.element_id);
            this.logs = resp || [];
        },
        formatTimestamp(time) {
            return formatTimestamp(time);
        },

        async editElement() {
            const response = await this.$refs.modalElementRef.open(this.parentWebpage.url, this.parentWebpage.webpage_id, this.element);
            if (response && response.success) {
                await this.getElementInfo();
            } 
        },
        async deleteElement() {
            if (await this.$refs.modalDeleteElementConfirmationRef.open()) {
                try {
                    const response = await fastApi.elements.delete(this.element.element_id);
                    if (response) {
                        this.$router.push(`/webpages/${this.parentWebpage.webpage_id}`);
                    }
                } catch {
                    const configStore = useConfigStore();
                    this.$notify(`Failed to delete element: ${configStore.read_only_mode ? 'Read-only mode' : 'Unknown error'}`);
                }
            }
        },
    },
    computed: {
        dataCount() {
            return this.data?.length || 0;
        }
    },
    async mounted() {
        await this.getElementInfo();
        await this.getParentWebpageInfo();
        await this.getElementData();
        await this.getElementLogs();
    }
}
</script>

<style scoped>
.element-details-grid {
    display: grid;
    gap: var(--card-gap);
    grid-template-columns: 400px 1fr 3fr;
    grid-template-areas:
        "a a a"
        "b b b"
        "d d c";
}
@media (max-width: 1400px) {
    .element-details-grid {
        grid-template-columns: 1fr;
            grid-template-areas:
            "a"
            "b"
            "c"
            "d";
    }
}

</style>