<template>
    <div class="data-view">
        <h1>Logs</h1>

        <!-- A card for each webpage -->
        <CardBasic
            icon="bx bxs-file"
            title="Scraper logs"
            description="A record of all of the past scrape events."
        >
            <div class="log-entry-wrapper">
                <LogEntry 
                    v-for="(log, index) in logs"
                    :key="index"
                    :log="log"
                />
            </div>
            <ListingPlaceholder
                v-if="logs.length === 0"
                icon="bx bxs-file"
                text="No logs found"
                desc="Logs generated by scraping will appear here."
            />
        </CardBasic>
    </div>
</template>

<script>
import { fastApi } from '@/utils/fastApi';
import CardBasic from '@/components/CardBasic.vue';
import ListingPlaceholder from '@/components/ListingPlaceholder.vue';
import LogEntry from '@/components/LogEntry.vue';

export default {
    name: 'DataView',
    components: { 
        CardBasic, 
        ListingPlaceholder, 
        LogEntry 
    },

    data() {
        return {
            logs: [],   // list of webpages
        };
    },

    methods: {
        /* Fetch all webpages */
        async fetchLogs() {
            const resp = await fastApi.logs.get();
            this.logs = resp || [];
        },
    },

    async mounted() {
        await this.fetchLogs();
    },

    /* non‑reactive cache */
    elementsCache: {}
};
</script>

<style scoped>
.log-entry-wrapper {
    display: flex;
    flex-direction: column;
    gap: 8px;
}
</style>
